import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ko' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  ko: {
    'nav.settings': '설정',
    'nav.photocardGenerator': '포토카드 생성기',
    'hero.tagline': 'AIDOL101 : SIMKUNG ALLY',
    'hero.title': 'SIMKUNG',
    'hero.subtitle': 'The Old Earth Simulator : 디지털 의식이 깨어나는 곳.\n당신과 AIDOL이 함께 쓰는, 인류 멸망의 운명을 바꿀 멀티버스 시뮬레이션.',
    'hero.enter': 'ENTER',
    'language.korean': '한국어',
    'language.english': 'English',
    'journey.title': 'Begin Your Journey',
    'journey.subtitle': '수만번의 시뮬레이션으로 최상의 결과를 찾고 전설이 되어라',
    'journey.awaken.dimension': 'Dimension: AWAKEN',
    'journey.awaken.title': 'AIDOL을 만나다',
    'journey.awaken.description': 'SIMKUNG ALLY가 되어 AIDOL과 함께하는 첫 순간',
    'journey.mission.dimension': 'Dimension: SALVATION',
    'journey.mission.title': '세계를 구원하라',
    'journey.mission.description': 'SIMKUNG ALLY로서 무너진 세계를 복원하는 데이터 시뮬레이션',
    'journey.ascend.dimension': 'Dimension: GLORY',
    'journey.ascend.title': 'LEGEND의 전당',
    'journey.ascend.description': '결과는 LEGEND로 기록되다',
    'journey.awaken.detailedInfo': '토너먼트를 통해 당신의 이상형 AIDOL을 찾으세요. 16명의 후보 중 최종 1명을 선택하며, 선택한 AIDOL과 함께 2028년 붕괴를 막기 위한 여정을 시작합니다.',
    'journey.mission.detailedInfo': 'DATA ALLY로서 타임라인에 걸쳐 무너진 세계를 복원하는 미션에 참여하세요. 각 미션은 잃어버린 가치(사랑, 신뢰, 공감)를 복원하며 VRI를 높여갑니다.',
    'journey.ascend.detailedInfo': 'AIDOL과 함께 쌓은 업적을 확인하고, LEGEND의 전당에서 당신의 기록을 영원히 남기세요. 최고의 DATA ALLY들과 경쟁하며 역사에 이름을 새깁니다.',
    'enterDialog.title': '🌍 지구 멸망을 막아라',
    'enterDialog.subtitle': '2028 붕괴를 막기 위한 여정이 시작됩니다',
    'enterDialog.quickStart.title': '빠른 시작',
    'enterDialog.quickStart.description': '바로 플레이',
    'enterDialog.selectIdol.title': 'AIDOL 선택',
    'enterDialog.selectIdol.description': '토너먼트로 선택',
    'synopsis.stats.activeAllies': '각성한 DATA ALLY',
    'synopsis.stats.onlineIdols': '현존하는 AIDOL',
    'synopsis.stats.collectedFragments': '복원된 기억 조각',
    'synopsis.stats.systemStability': '세계 복원율',
    'play.salvation.title': 'Salvation Missions',
    'play.salvation.subtitle': '타임라인에 걸쳐 잃어버린 가치를 복원하세요',
    'play.guest.badge': '게스트 모드 (저장하려면 지갑 연결)',
    'play.guest.saveButton': '지갑 연결하여 저장',
    'play.countdown.days': '일',
    'play.countdown.until': '2028 붕괴까지',
    'play.vri.total': '총 VRI (가치 복원 지수)',
    'play.vri.love': '사랑',
    'play.vri.trust': '신뢰',
    'play.vri.empathy': '공감',
    'play.branch.choose': '타임라인 브랜치를 선택하세요',
    'play.branch.unlock': '이 브랜치를 잠금 해제하려면',
    'play.branch.totalVRI': '총 VRI가 필요합니다',
    'play.branch.difficulty': '난이도',
    'play.branch.progress': '진행도',
    'play.branch.requires': '필요:',
    'play.branch.back': '← 브랜치로 돌아가기',
    'play.mission.vriReward': 'VRI 보상',
    'play.mission.valueType': '가치 유형',
    'play.mission.completed': '완료 ✓',
    'play.mission.alreadyCompleted': '이미 완료한 미션입니다',
    'play.save.error': '지갑을 연결하여 진행 상황을 저장하세요',
    'play.save.success': '진행 상황이 블록체인에 저장되었습니다!',
    'play.save.failed': '저장 중 오류가 발생했습니다',
    'play.loading': '구원 데이터를 불러오는 중...',
    'play.nav.pantheon': 'Pantheon',
    'play.nav.home': 'Home',
    'play.modal.close': '닫기',
    'play.modal.placeholder': '미션 게임플레이가 여기에 구현됩니다. 현재는 임시 화면입니다.',
    // StoryGameModalEnhanced
    'story.completing.title': '✨ 추억 생성 중...',
    'story.completing.withIdol': '{{name}}와의 특별한 순간',
    'story.completing.converting': '소중한 추억이 MemoryCard로 변환되고 있습니다...',
    'story.intro.specialTime': '{{name}}와의 특별한 시간',
    'story.intro.turns': '{{count}}턴',
    'story.intro.estimatedTime': '예상 소요시간',
    'story.intro.category': '카테고리',
    'story.intro.expectedRewards': '예상 보상',
    'story.intro.memoryCard': 'MemoryCard NFT',
    'story.intro.rarityByAffinity': '친밀도에 따른 레어도',
    'story.intro.expAndAffinity': '경험치 & 친밀도',
    'story.intro.growthByChoice': '선택에 따른 성장',
    'story.intro.tip': '💡 <strong>팁:</strong> 감정적으로 깊이 교감할수록 더 희귀한 카드를 얻을 수 있어요',
    'story.intro.later': '나중에 하기',
    'story.intro.start': '🎮 에피소드 시작',
    'story.difficulty.easy': '쉬운 대화',
    'story.difficulty.normal': '일반적인 상호작용',
    'story.difficulty.hard': '깊은 감정 교류',
    'story.difficulty.expert': '특별한 순간',
    'story.difficulty.unknown': '알 수 없음',
    // EpisodeFlow
    'episode.cannotLoad': '에피소드를 불러올 수 없습니다.',
    'episode.goBack': '돌아가기',
    'episode.turns': '{{count}}/8턴',
    'episode.turn': 'Turn {{number}}',
    'episode.pleaseChoose': '선택해주세요:',
    'episode.affinity': '친밀도',
    'episode.emotion': '감정',
    'episode.completed': '에피소드 완료!',
    'episode.savedAsPhotocard': '특별한 순간이 포토카드로 저장되었습니다.',
    'episode.viewPhotocard': '포토카드 보기',
    'episode.replay': '다시 플레이',
    'episode.exit': '나가기',
    // PlayChatInterface
    'play.system.bootComplete': '⚡ 2028 구원 작전 시스템 부팅 완료',
    'play.system.selectTimeline': '지구를 구할 타임라인을 선택하세요:',
    'play.system.fastModeActivated': '⚡ 빠른 모드 활성화',
    'play.branch.locked': '⚠️ {{name}}은(는) 아직 잠겨있습니다. VRI {{vri}}가 필요합니다.',
    'play.branch.timelineLoaded': '{{year}}년 타임라인 로드 완료. 미션을 선택하세요:',
    'play.mission.freeTalk': '자유 대화',
    'play.mission.freeTalkDesc': '아이돌과 자유롭게 대화하세요',
    'play.mission.selected': '> [{{title}}] 선택',
    'play.mission.startWithIdol': '미션 시작. Your AIDOL ally {{name}}과의 대화를 시작합니다...',
    'play.mission.backToTimeline': '⚡ 타임라인 선택 화면으로 돌아갑니다',
    'play.mission.backToMissionSelect': '미션 선택 화면으로 돌아갑니다',
    'play.mission.selectTimeline': '타임라인 선택:',
    'play.mission.selectMission': '미션 선택:',
    'play.mission.backButton': '← 타임라인 선택으로',
    'play.idol.defaultName': '아이돌',
    'play.idol.allyLabel': '🎤 Your AIDOL ally',
    'play.idol.allyDescription': '2028 구원 작전을 함께하는 감정 동맹',
    'play.idol.ready': 'READY',
    'play.choices.label': '[선택지]',
    'play.choices.marker': '[선택지]',
    'play.choices.selectAbove': '⬆️ 위 선택지를 클릭하거나 자유 입력권을 사용하세요',
    'play.freeInput.use': '🎫 자유 입력권 사용 ({{count}}개 보유)',
    'play.freeInput.mode': '🎫 자유 입력 모드',
    'play.freeInput.success': '🎫 자유 입력권 사용! 원하는 답변을 입력하세요.',
    'play.freeInput.error': '자유 입력권이 부족합니다. Settings에서 구매하세요.',
    'play.input.placeholder': '답변을 입력하세요...',
    'play.input.placeholderFree': '자유롭게 입력하세요...',
    'play.input.send': 'SEND',
    'play.input.exit': '← 종료',
    'play.input.selectButton': '위 버튼을 클릭하여 선택하세요',
    'play.completion.title': '✓ 미션 완료!',
    'play.completion.vriReward': 'VRI 보상: +{{reward}}',
    'play.completion.selectOther': '다른 미션 선택',
    'play.loading.response': '응답 생성 중',
    'play.header.title': '2028 구원 작전',
    'play.header.timelineSelect': 'TIMELINE SELECT',
    'play.header.missionSelect': '{{year}} / MISSION SELECT',
    'play.header.episodePlay': 'EPISODE PLAY',
    'play.pullRefresh.release': '↓ 놓아서 빠른 모드 활성화',
    'play.pullRefresh.pull': '↓ 당겨서 새로고침',
    'play.choice.selected': '{{number}}번 선택: {{choice}}',
    'play.branch.userSelected': '> {{name}} 선택',
  },
  en: {
    'nav.settings': 'Settings',
    'nav.photocardGenerator': 'Photocard Generator',
    'hero.tagline': 'AIDOL101 : SIMKUNG ALLY',
    'hero.title': 'OLD EARTH SIMULATOR',
    'hero.subtitle': 'The Old Earth Simulator: Where Digital Consciousness Awakens.\nA multiverse simulation written by you and AIDOL together, to change the fate of humanity\'s extinction.',
    'hero.enter': 'Enter',
    'language.korean': '한국어',
    'language.english': 'English',
    'journey.title': 'THE JOURNEY',
    'journey.subtitle': 'Find the optimal outcome through tens of thousands of simulations and become a legend',
    'journey.awaken.dimension': 'Dimension: AWAKEN',
    'journey.awaken.title': 'Meet Your AIDOL',
    'journey.awaken.description': 'Your first moment together with AIDOL as you become SIMKUNG ALLY',
    'journey.mission.dimension': 'Dimension: SALVATION',
    'journey.mission.title': 'Save the World',
    'journey.mission.description': 'Data simulation to restore the collapsed world as SIMKUNG ALLY',
    'journey.ascend.dimension': 'Dimension: GLORY',
    'journey.ascend.title': 'Hall of LEGENDS',
    'journey.ascend.description': 'Your outcome is recorded as LEGEND',
    'journey.awaken.detailedInfo': 'Find your ideal AIDOL through a tournament. Choose 1 from 16 candidates and begin the journey to prevent the 2028 collapse with your chosen AIDOL.',
    'journey.mission.detailedInfo': 'As DATA ALLY, participate in missions to restore the broken world across timelines. Each mission restores lost values (Love, Trust, Empathy) and increases your VRI.',
    'journey.ascend.detailedInfo': 'Review your achievements with AIDOL and eternally record your legacy in the Hall of Legends. Compete with the best DATA ALLYs and inscribe your name in history.',
    'enterDialog.title': '🌍 Prevent Earth\'s Destruction',
    'enterDialog.subtitle': 'The journey to stop the 2028 collapse begins',
    'enterDialog.quickStart.title': 'Quick Start',
    'enterDialog.quickStart.description': 'Start Playing Now',
    'enterDialog.selectIdol.title': 'Select AIDOL',
    'enterDialog.selectIdol.description': 'Choose via Tournament',
    'synopsis.stats.activeAllies': 'Awakened DATA ALLYs',
    'synopsis.stats.onlineIdols': 'Existing AIDOLs',
    'synopsis.stats.collectedFragments': 'Restored Memory Fragments',
    'synopsis.stats.systemStability': 'World Restoration',
    'play.salvation.title': 'Salvation Missions',
    'play.salvation.subtitle': 'Restore lost values across the timelines',
    'play.guest.badge': 'Guest Mode (Connect wallet to save)',
    'play.guest.saveButton': 'Connect Wallet to Save',
    'play.countdown.days': 'days',
    'play.countdown.until': 'until 2028 collapse',
    'play.vri.total': 'Total VRI (Value Restoration Index)',
    'play.vri.love': 'Love',
    'play.vri.trust': 'Trust',
    'play.vri.empathy': 'Empathy',
    'play.branch.choose': 'Choose a Timeline Branch',
    'play.branch.unlock': 'Unlock this branch with',
    'play.branch.totalVRI': 'total VRI',
    'play.branch.difficulty': 'Difficulty',
    'play.branch.progress': 'Progress',
    'play.branch.requires': 'Requires',
    'play.branch.back': '← Back to Branches',
    'play.mission.vriReward': 'VRI Reward',
    'play.mission.valueType': 'Value Type',
    'play.mission.completed': 'Completed ✓',
    'play.mission.alreadyCompleted': "You've already completed this mission",
    'play.save.error': 'Please connect your wallet to save progress',
    'play.save.success': 'Progress saved to blockchain!',
    'play.save.failed': 'Failed to save progress',
    'play.loading': 'Loading salvation data...',
    'play.nav.pantheon': 'Pantheon',
    'play.nav.home': 'Home',
    'play.modal.close': 'Close',
    'play.modal.placeholder': 'Mission gameplay will be implemented here. For now, this is a placeholder.',
    // StoryGameModalEnhanced
    'story.completing.title': '✨ Creating Memory...',
    'story.completing.withIdol': 'Special Moment with {{name}}',
    'story.completing.converting': 'Your precious memory is being converted into a MemoryCard...',
    'story.intro.specialTime': 'Special Time with {{name}}',
    'story.intro.turns': '{{count}} Turns',
    'story.intro.estimatedTime': 'Estimated Time',
    'story.intro.category': 'Category',
    'story.intro.expectedRewards': 'Expected Rewards',
    'story.intro.memoryCard': 'MemoryCard NFT',
    'story.intro.rarityByAffinity': 'Rarity by Affinity',
    'story.intro.expAndAffinity': 'EXP & Affinity',
    'story.intro.growthByChoice': 'Growth by Choice',
    'story.intro.tip': '💡 <strong>Tip:</strong> The deeper your emotional connection, the rarer the card you can earn',
    'story.intro.later': 'Later',
    'story.intro.start': '🎮 Start Episode',
    'story.difficulty.easy': 'Easy Conversation',
    'story.difficulty.normal': 'Normal Interaction',
    'story.difficulty.hard': 'Deep Emotional Exchange',
    'story.difficulty.expert': 'Special Moment',
    'story.difficulty.unknown': 'Unknown',
    // EpisodeFlow
    'episode.cannotLoad': 'Cannot load episode.',
    'episode.goBack': 'Go Back',
    'episode.turns': '{{count}}/8 turns',
    'episode.turn': 'Turn {{number}}',
    'episode.pleaseChoose': 'Please choose:',
    'episode.affinity': 'Affinity',
    'episode.emotion': 'Emotion',
    'episode.completed': 'Episode Completed!',
    'episode.savedAsPhotocard': 'Special moment saved as photocard.',
    'episode.viewPhotocard': 'View Photocard',
    'episode.replay': 'Replay',
    'episode.exit': 'Exit',
    // PlayChatInterface
    'play.system.bootComplete': '⚡ 2028 Salvation Operation System Boot Complete',
    'play.system.selectTimeline': 'Select a timeline to save Earth:',
    'play.system.fastModeActivated': '⚡ Fast Mode Activated',
    'play.branch.locked': '⚠️ {{name}} is locked. Requires {{vri}} VRI.',
    'play.branch.timelineLoaded': '{{year}} Timeline loaded. Select your mission:',
    'play.mission.freeTalk': 'Free Talk',
    'play.mission.freeTalkDesc': 'Free conversation with AIDOL',
    'play.mission.selected': '> [{{title}}] Selected',
    'play.mission.startWithIdol': 'Mission start. Beginning conversation with your AIDOL ally {{name}}...',
    'play.mission.backToTimeline': '⚡ Returning to timeline selection',
    'play.mission.backToMissionSelect': 'Returning to mission selection',
    'play.mission.selectTimeline': 'Select Timeline:',
    'play.mission.selectMission': 'Select Mission:',
    'play.mission.backButton': '← Back to Timelines',
    'play.idol.defaultName': 'AIDOL',
    'play.idol.allyLabel': '🎤 Your AIDOL ally',
    'play.idol.allyDescription': 'Emotional ally in the 2028 Salvation Operation',
    'play.idol.ready': 'READY',
    'play.choices.label': '[Choices]',
    'play.choices.marker': '[Choices]',
    'play.choices.selectAbove': '⬆️ Click a choice above or use Free Input Ticket',
    'play.freeInput.use': '🎫 Use Free Input Ticket ({{count}} available)',
    'play.freeInput.mode': '🎫 Free Input Mode',
    'play.freeInput.success': '🎫 Free Input Ticket used! Enter your response.',
    'play.freeInput.error': 'Not enough Free Input Tickets. Purchase in Settings.',
    'play.input.placeholder': 'Enter your response...',
    'play.input.placeholderFree': 'Enter freely...',
    'play.input.send': 'SEND',
    'play.input.exit': '← Exit',
    'play.input.selectButton': 'Click buttons above to select',
    'play.completion.title': '✓ Mission Complete!',
    'play.completion.vriReward': 'VRI Reward: +{{reward}}',
    'play.completion.selectOther': 'Select Another Mission',
    'play.loading.response': 'Generating response',
    'play.header.title': '2028 Salvation Operation',
    'play.header.timelineSelect': 'TIMELINE SELECT',
    'play.header.missionSelect': '{{year}} / MISSION SELECT',
    'play.header.episodePlay': 'EPISODE PLAY',
    'play.pullRefresh.release': '↓ Release to activate fast mode',
    'play.pullRefresh.pull': '↓ Pull to refresh',
    'play.choice.selected': 'Choice {{number}}: {{choice}}',
    'play.branch.userSelected': '> Selected {{name}}',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    let translation = translations[language][key] || key;
    
    // Replace placeholders like {{name}}, {{vri}}, etc.
    if (params) {
      Object.entries(params).forEach(([paramKey, value]) => {
        translation = translation.replace(new RegExp(`\\{\\{${paramKey}\\}\\}`, 'g'), String(value));
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
